# Generated by Django 5.2.8 on 2025-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
