# Generated by Django 5.2.8 on 2025-11-11 09:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bankaccount_notification_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('circle', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RechargePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(blank=True, max_length=80)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.operator')),
            ],
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('upi_tid', models.CharField(blank=True, max_length=200)),
                ('provider_txn', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rechargeplan')),
            ],
        ),
    ]
