# Generated by Django 5.2.8 on 2025-11-12 07:10

import builtins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_operator_rechargeplan_rechargeorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='razorpay_signature',
        ),
        migrations.AddField(
            model_name='transaction',
            name='txn_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_upi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
