# Generated by Django 5.2.8 on 2025-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_modified_at_transaction_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_num',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
