"""
Django settings for upi_project project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path
import os
from pathlib import Path

# Optional: load .env file in development. Install python-dotenv: pip install python-dotenv
from dotenv import load_dotenv

# Project base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root if present
env_path = BASE_DIR / '.env'
if env_path.exists():
    load_dotenv(env_path)

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable, fallback to an obviously insecure default (only dev)
SECRET_KEY = os.getenv('SECRET_KEY', 'replace-me-with-a-secret-in-production')

# DEBUG from env; default False for safety (set True only locally)
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')

# ALLOWED_HOSTS can be comma separated in .env
allowed = os.getenv('ALLOWED_HOSTS', '')
if allowed:
    ALLOWED_HOSTS = [h.strip() for h in allowed.split(',')]
else:
    ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'core.User'

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'upi_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'upi_project.wsgi.application'

# Database (unchanged)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation (unchanged)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Static files
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [ BASE_DIR / 'core' / 'static', ]
STATIC_URL = 'static/'

# Internationalization (unchanged)
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'   # ✅ Indian Standard Time
USE_I18N = True               # ✅ enables internationalization
USE_TZ = True 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------- External service credentials (from env) ----------------
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')

RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')

# If you want, you can also ensure required secrets are present in production:
REQUIRE_SECRETS = os.getenv('REQUIRE_SECRETS', 'False').lower() in ('1','true','yes')
if REQUIRE_SECRETS and (not SECRET_KEY or SECRET_KEY == 'replace-me-with-a-secret-in-production'):
    raise RuntimeError('Missing SECRET_KEY in environment!')

# End of settings.py
import os

_raw_allowed = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _raw_allowed.split(",") if h.strip()]

# fallback to localhost if none provided (optional)
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# # settings.py (prod)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True           # or EMAIL_USE_SSL = True with port 465
# EMAIL_HOST_USER = 'mathivarmaganesan@gmail.com'
# EMAIL_HOST_PASSWORD = 'ryib qgbq lktw iwhfd'
# DEFAULT_FROM_EMAIL = 'devakimathivarma@gmail.com'

import os

# --- Email (use env vars) ---
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')

# For Gmail / general SMTP
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'   # True for port 587
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')   # e.g. "you@gmail.com"
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # store in env or secret manager

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@yourdomain.com')
DEFAULT_NOTIFICATION_EMAIL = os.getenv('DEFAULT_NOTIFICATION_EMAIL', DEFAULT_FROM_EMAIL)


